### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ethanhuang13** [ethanhuang13/CupertinoJWT#3]

**Comment by JanC** [comment]
Hi,
FYI, the Carthage support already works. You just need to add it to the readme:

```markdown
### Carthage

[Carthage][] is a simple, decentralized dependency manager for Cocoa. To install CupertinoJWT with Carthage:

 1. Make sure Carthage is [installed][Carthage Installation].

 2. Update your Cartfile to include the following:

    ```ruby
      github "ethanhuang13/CupertinoJWT"
    ```

 3. Run `carthage update` and [add the appropriate framework][Carthage Usage].

[Carthage]: https://github.com/Carthage/Carthage
[Carthage Installation]: https://github.com/Carthage/Carthage#installing-carthage
[Carthage Usage]: https://github.com/Carthage/Carthage#adding-frameworks-to-an-application
```

**Comment by ethanhuang13** [comment]
Thank you. I tried and it works. Updated README.md.

**Comment by JanC** [comment]
Actually I spoke too fast. The current project still needs targets for the other platforms in order to compile with Carthage. I'll make a PR

**Comment by ethanhuang13** [comment]
You mean platforms other than iOS?

**Comment by JanC** [comment]
yep. There should be one target per platform e.g. `CupertinoJWT iOS`, `CupertinoJWT macOS` ..
